[package]
name = "rusty-rails"
version = "0.1.0"
authors = ["Jaden Carver <jaden.carver@gmail.com>"]

[dependencies]
iron = "^0.2"
persistent = "^0.0.9"
router = "^0.1"
params = "^0.0.2"
maud = { git = "https://github.com/lfairy/maud.git" }
maud_macros = { git = "https://github.com/lfairy/maud.git" }
logger = "^0.0.3"
clap = "^2.1.2"
staticfile = { version = "^0.1", features = ["cache"] }
glob = "^0.2.10"
diesel = "^0.5.0"
diesel_codegen = { version = "^0.5.0", default-features = false, features = ["nightly", "postgres"], git = "https://github.com/sgrif/diesel.git" }
diesel_cli = "^0.5.1"
dotenv = "^0.8.0"
dotenv_macros = "^0.8.0"
serde = "^0.6"
serde_json = "^0.6"
r2d2 = "^0.6"
r2d2-diesel = { version = "^0.5.0", git = "https://github.com/sgrif/r2d2-diesel.git" }
ansi_term = "^0.7.1"
notify = "^2.5.0"
websocket = "^0.15.0"

[[bin]]
name = "start"
path = "src/monitor.rs"

[[bin]]
name = "server"
path = "app/server.rs"

[[bin]]
name = "task"
path = "src/task.rs"

[[bin]]
name = "generate"
path = "src/generate.rs"
